### ISSUE TITLE
[terraform-ibm-scc-workload-protection] Add support to connect a Monitoring instance

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-scc-workload-protection#61]
Looks like its possible in the UI to connect a Monitoring instance to a workload protection instance at provision time. The module should be updated to also support this:

![image](https://github.com/terraform-ibm-modules/terraform-ibm-scc-workload-protection/assets/29608224/e5093a2f-a48c-4794-b51f-18970adfee43)

**Comment by jor2** [comment]
I don't see an option to connect a monitoring instance in the [provider](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/scc_instance) code.

**Comment by ocofaigh** [comment]
This feature was already added in https://github.com/terraform-ibm-modules/terraform-ibm-scc-workload-protection/releases/tag/v1.2.0
